
sudo: false
language: java
jdk:
  - oraclejdk8
  
addons:
   apt:
   packages:
   - oracle-java8-installer

  
  
script: mvn test

skip_cleanup: true
  
  
after_success:
  ./.travis/artifact-upload.sh


  
  
 

