sudo: false
language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - "$HOME/.cache"
install: mvn dependency:resolve
deploy:
  provider: script
  script: mvn clean verify
  skip_cleanup: true
  on:
    tags: true

